-- ============================================================
-- FILE: db/schema/04_jobs.sql
-- Module: Jobs / Work Orders
-- Depends on: 01_users.sql, 02_technicians.sql, 03_clients.sql
-- Run AFTER 01, 02, 03
-- ============================================================

-- NOTE: pg_trgm extension and set_updated_at() function are
-- already created in 01_users.sql — no need to repeat them here.

-- ─── ENUM: job_status ────────────────────────────────────────

DO $$ BEGIN
  CREATE TYPE job_status AS ENUM (
    'Raised',
    'Assigned',
    'In Progress',
    'Closed'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

-- ─── ENUM: job_priority ──────────────────────────────────────

DO $$ BEGIN
  CREATE TYPE job_priority AS ENUM (
    'Low',
    'Medium',
    'High',
    'Critical'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

-- ─── ENUM: job_category ──────────────────────────────────────

DO $$ BEGIN
  CREATE TYPE job_category AS ENUM (
    'Maintenance',
    'Repair',
    'Installation',
    'Inspection'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

-- ─── TABLE: jobs ─────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS jobs (
  id                VARCHAR(20)   PRIMARY KEY,
  title             VARCHAR(255)  NOT NULL,
  description       TEXT,
  client_id         INTEGER       NOT NULL REFERENCES clients(id)     ON DELETE RESTRICT,
  technician_id     INTEGER                REFERENCES technicians(id) ON DELETE SET NULL,
  status            job_status    NOT NULL DEFAULT 'Raised',
  priority          job_priority  NOT NULL DEFAULT 'Medium',
  category          job_category  NOT NULL DEFAULT 'Maintenance',
  amount            NUMERIC(12,2) DEFAULT 0.00,
  raised_date       DATE          NOT NULL DEFAULT CURRENT_DATE,
  scheduled_date    DATE,
  closed_date       DATE,
  raised_by_user_id INTEGER                REFERENCES users(id)       ON DELETE SET NULL,
  created_at        TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

  CONSTRAINT jobs_closed_needs_technician CHECK (
    status != 'Closed' OR technician_id IS NOT NULL
  ),
  CONSTRAINT jobs_closed_date_required CHECK (
    status != 'Closed' OR closed_date IS NOT NULL
  )
);

COMMENT ON TABLE  jobs                   IS 'Work orders — raised, assigned, progressed, and closed';
COMMENT ON COLUMN jobs.id                IS 'Business ID format JOB-NNNN, generated by application';
COMMENT ON COLUMN jobs.closed_date       IS 'Set to CURRENT_DATE when status transitions to Closed';
COMMENT ON COLUMN jobs.raised_by_user_id IS 'The admin/staff user who created the job record';

-- ─── TABLE: job_images ───────────────────────────────────────

CREATE TABLE IF NOT EXISTS job_images (
  id                  SERIAL        PRIMARY KEY,
  job_id              VARCHAR(20)   NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
  file_name           VARCHAR(255)  NOT NULL,
  file_url            TEXT          NOT NULL,
  file_size_bytes     INTEGER,
  mime_type           VARCHAR(100)  DEFAULT 'image/jpeg',
  uploaded_by_user_id INTEGER       REFERENCES users(id) ON DELETE SET NULL,
  uploaded_at         TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE  job_images          IS 'Images attached to a job';
COMMENT ON COLUMN job_images.file_url IS 'Full HTTPS URL to the uploaded file';

-- ─── TRIGGER: jobs ───────────────────────────────────────────

DROP TRIGGER IF EXISTS trg_jobs_updated_at ON jobs;
CREATE TRIGGER trg_jobs_updated_at
  BEFORE UPDATE ON jobs
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

-- ─── INDEXES: jobs ───────────────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_jobs_client_id     ON jobs (client_id);
CREATE INDEX IF NOT EXISTS idx_jobs_technician_id ON jobs (technician_id);
CREATE INDEX IF NOT EXISTS idx_jobs_status        ON jobs (status);
CREATE INDEX IF NOT EXISTS idx_jobs_priority      ON jobs (priority);
CREATE INDEX IF NOT EXISTS idx_jobs_raised_date   ON jobs (raised_date DESC);

CREATE INDEX IF NOT EXISTS idx_jobs_scheduled_date
  ON jobs (scheduled_date) WHERE scheduled_date IS NOT NULL;

-- GIN index for fuzzy title search
-- pg_trgm extension was enabled in 01_users.sql
CREATE INDEX IF NOT EXISTS idx_jobs_title_trgm
  ON jobs USING GIN (title gin_trgm_ops);

-- ─── INDEXES: job_images ─────────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_job_images_job_id ON job_images (job_id);
