-- ============================================================
-- FILE: db/schema/04_jobs.sql
-- Module: Jobs / Work Orders
-- Depends on: 01_users.sql, 02_technicians.sql, 03_clients.sql
-- Run AFTER 01, 02, 03
-- ============================================================


-- ─── ENUM: job_status ────────────────────────────────────────

DO $$ BEGIN
  CREATE TYPE job_status AS ENUM (
    'Raised',
    'Assigned',
    'In Progress',
    'Closed'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;


-- ─── ENUM: job_priority ──────────────────────────────────────

DO $$ BEGIN
  CREATE TYPE job_priority AS ENUM (
    'Low',
    'Medium',
    'High',
    'Critical'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;


-- ─── ENUM: job_category ──────────────────────────────────────

DO $$ BEGIN
  CREATE TYPE job_category AS ENUM (
    'Maintenance',
    'Repair',
    'Installation',
    'Inspection'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;


-- ─── TABLE: jobs ─────────────────────────────────────────────
-- Work orders — the core operational entity.
-- id format: JOB-NNNN (e.g. JOB-0001, JOB-0042)
-- Generated by application layer (not a DB sequence).

CREATE TABLE IF NOT EXISTS jobs (
  id                VARCHAR(20)    PRIMARY KEY,
  title             VARCHAR(255)   NOT NULL,
  description       TEXT,
  client_id         INTEGER        NOT NULL REFERENCES clients(id)     ON DELETE RESTRICT,
  technician_id     INTEGER        REFERENCES technicians(id)          ON DELETE SET NULL,
  status            job_status     NOT NULL DEFAULT 'Raised',
  priority          job_priority   NOT NULL DEFAULT 'Medium',
  category          job_category   NOT NULL DEFAULT 'Maintenance',
  amount            NUMERIC(12,2)  DEFAULT 0.00,
  raised_date       DATE           NOT NULL DEFAULT CURRENT_DATE,
  scheduled_date    DATE,
  closed_date       DATE,
  -- closed_date is set automatically when status transitions to Closed
  raised_by_user_id INTEGER        REFERENCES users(id)                ON DELETE SET NULL,
  created_at        TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ    NOT NULL DEFAULT NOW(),

  -- A job can only be closed if a technician is assigned
  CONSTRAINT jobs_closed_needs_technician CHECK (
    status != 'Closed' OR technician_id IS NOT NULL
  ),
  -- closed_date must be set when status is Closed
  CONSTRAINT jobs_closed_date_required CHECK (
    status != 'Closed' OR closed_date IS NOT NULL
  )
);

COMMENT ON TABLE  jobs                    IS 'Work orders — raised, assigned, progressed, and closed by operations team';
COMMENT ON COLUMN jobs.id                 IS 'Business ID format JOB-NNNN, generated by application layer';
COMMENT ON COLUMN jobs.raised_by_user_id  IS 'The admin/staff user who created the job record';
COMMENT ON COLUMN jobs.closed_date        IS 'Set automatically to CURRENT_DATE when status transitions to Closed';


-- ─── TABLE: job_images ───────────────────────────────────────
-- Images attached to a job (site photos, evidence, etc.).
-- Actual files are stored in external object storage (S3/R2).
-- Only the URL and metadata are stored here.

CREATE TABLE IF NOT EXISTS job_images (
  id                    SERIAL       PRIMARY KEY,
  job_id                VARCHAR(20)  NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
  file_name             VARCHAR(255) NOT NULL,
  file_url              TEXT         NOT NULL,   -- Full HTTPS URL to file in object storage
  file_size_bytes       INTEGER,
  mime_type             VARCHAR(100) DEFAULT 'image/jpeg',
  uploaded_by_user_id   INTEGER      REFERENCES users(id) ON DELETE SET NULL,
  uploaded_at           TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE  job_images          IS 'Images attached to a job — stored in external object storage, URL recorded here';
COMMENT ON COLUMN job_images.file_url IS 'Full HTTPS URL to the uploaded file in object storage';


-- ─── TRIGGER: jobs updated_at ────────────────────────────────

DROP TRIGGER IF EXISTS trg_jobs_updated_at ON jobs;
CREATE TRIGGER trg_jobs_updated_at
  BEFORE UPDATE ON jobs
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();


-- ─── INDEXES: jobs ───────────────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_jobs_client_id      ON jobs (client_id);
CREATE INDEX IF NOT EXISTS idx_jobs_technician_id  ON jobs (technician_id);
CREATE INDEX IF NOT EXISTS idx_jobs_status         ON jobs (status);
CREATE INDEX IF NOT EXISTS idx_jobs_priority       ON jobs (priority);
CREATE INDEX IF NOT EXISTS idx_jobs_raised_date    ON jobs (raised_date DESC);

CREATE INDEX IF NOT EXISTS idx_jobs_scheduled_date
  ON jobs (scheduled_date)
  WHERE scheduled_date IS NOT NULL;

-- Fuzzy text search on job title
CREATE INDEX IF NOT EXISTS idx_jobs_title_trgm
  ON jobs USING GIN (title gin_trgm_ops);


-- ─── INDEXES: job_images ─────────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_job_images_job_id ON job_images (job_id);
